config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index' => 'home#index'

  devise_for :users,:controllers => {
        :registrations => 'users/registrations',
        :sessions => 'users/sessions',
        omniauth_callbacks: "users/omniauth_callbacks"
    }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  resources :shops
  resources :stylists

  get 'thank' => 'thank#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base.rb
class Base < ApplicationRecord
	has_many :stylists
end

app/models/basis.rb
class Basis < ApplicationRecord
end

app/models/hairstyle.rb
class Hairstyle < ApplicationRecord
	has_many :stylists
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :shop, optional: true
  	mount_uploader :image_url, ImageUploader
end

app/models/recommend.rb
class Recommend < ApplicationRecord
	has_many :shops
end

app/models/seet.rb
# class Seet < ApplicationRecord
# 	has_many :shops
# end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :user

	# belongs_to :seet

	has_many :images, dependent: :destroy
  	accepts_nested_attributes_for :images, allow_destroy: true

	geocoded_by :address
  	after_validation :geocode, if: :address_changed?, latitude: :latitude, longitude: :longitude
end

app/models/stylist.rb
class Stylist < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :base
	has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
  		   :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :omniauthable,
         omniauth_providers:%i(google)

  has_many :shops, dependent: :destroy
  has_many :stylists, dependent: :destroy

  protected
    def self.find_for_google(auth)
      user = User.find_by(email: auth.info.email)
      unless user
        user = User.create(name:     auth.info.name,
                          provider: auth.provider,
                          uid:      auth.uid,
                          token:    auth.credentials.token,
                          email:    auth.info.email,
                          password: Devise.friendly_token[0, 20],
                          meta:     auth.to_yaml)
      end
      user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    case resource
    # when Admin
    #   admin_posts_path
    when current_user
      home_index_path
    end
  end

#   def after_inactive_sign_up_path_for(resource)
#     case resource
#     # when Admin
#     #   admin_posts_path
#     root_path
#   end


# 　def after_sign_out_path_for(resource)
#   case resource
#     # when Admin
#     #   admin_posts_path
# 　  root_path
# 　end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
before_action :authenticate_user!,:ensure_correct_user,{only: [:edit, :update]}

  def new
    @shop = Shop.new
    @shop.images.build
  end

  def create
    @shop = Shop.create(shop_params)
    if @shop.save
      redirect_to shops_path , notice: '作成しました'
    else
      render 'index'
    end
  end

  def index
    @shops = Shop.page(params[:page]).per(12)
  end

  def show
    @shop = Shop.find(params[:id])
    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow shop.address
      marker.json({ address: shop.address })
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params)
    redirect_to shops_path
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path
  end



  private
    def shop_params
      params.require(:shop).permit(:name,
                                   :description,
                                   :address,
                                   :latitude,
                                   :longitude,
                                   :user_id,
                                   :seet_id,
                                   :recommend_id,
                                   images_attributes: [:image_url]
                                )
    end

    def ensure_correct_user
      @shop = Shop.find(params[:id])
      if current_user != @shop.user
        redirect_to shops_path
      end
    end


end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
before_action :authenticate_user!,:ensure_correct_user,{only: [:edit, :update]}

  def new
    @stylist = Stylist.new
  end

  def create
    @stylist = Stylist.new(stylist_params)
    if @stylist.save
      redirect_to stylists_path
    else
      render 'new'
    end
  end

  def index
    @stylists = Stylist.page(params[:page]).per(12)
  end

  def show
    @stylist = Stylist.find(params[:id])
    @stylists = Stylist.all
  end

  def edit
    @stylist = Stylist.find(params[:id])
  end

  def update
    @stylist = Stylist.find(params[:id])
    @stylist.update(stylist_params)
    redirect_to stylists_path
  end

  def destroy
    @stylist = Stylist.find(params[:id])
    @stylist.destroy
    redirect_to stylists_path
  end

private
  def stylist_params
    params.require(:stylist).permit(  :last_name,
                                      :first_name,
                                      :last_name_kana,
                                      :first_name_kana,
                                      :birthday,
                                      :email,
                                      :password,
                                      :name,
                                      :base_id,
                                      :user_id,
                                      :recommend_id,
                                      :career_years,
                                      :skilled_style1,
                                      :skilled_style2,
                                      :description,
                                      images: []
                                  )
  end

  def ensure_correct_user
    @stylist = Stylist.find(params[:id])
    if current_user != @stylist.user
      redirect_to stylists_path
    end
  end

end

app/controllers/thank_controller.rb
class ThankController < ApplicationController
  def index
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/helpers/thank_helper.rb
module ThankHelper
end

app/views/shops/edit.html.erb
<h1>店舗編集画面</h1>
<%= form_with model: @shop, local: true do |f| %>

  <div><%= f.label :名称 %></div>
  <div><%= f.text_field :name %></div>

  <div><%= f.label :内容 %></div>
  <div><%= f.text_field :description %></div>

  <div><%= f.label :席数 %></div>
  <div><%= f.collection_select :seet_id, Seet.all,:id,:seet %></div>

  <div><%= f.label :こんな人にオススメ！！ %></div>
  <div><%= f.collection_select :recommend_id, Recommend.all,:id,:text %></div>

  <div><%= f.label :場所 %></div>
  <div><%= f.text_field :address, placeholder: "住所" %></div>

  <div><%= f.label :店舗写真 %></div>
  <div><%= f.file_field :image, multiple: true %></div>

  <div><%= f.submit %></div>
<% end %>

<%= link_to '戻る', shops_path %>
<%= link_to ' ログアウト ',destroy_user_session_path, method: :delete%>

app/views/shops/index.html.erb
<table>
  <thead>
    <tr>
      <td></td>
      <td>名称</td>
      <td>内容</td>
      <td>店舗写真</td>
      <td>場所・住所</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.id %></td>
        <td><%= shop.name %></td>
        <td><%= shop.description %></td>
        <td>
          <% shop.images.each do |i| %>
           <%= image_tag i.image_url.to_s[0] , width: '100%', height: '100%'%>
          <% end %>
        </td>

        <td><%= shop.address %></td>
        <td><%= link_to '詳細', shop_path(shop) %></td>
        <td><%= shop.user_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
    <div class="col-sm-10 col-sm-offset-1" style="text-align:center; padding:20px; font-size: 25px;">
        <%= paginate @shops, class: "paginate" %>
    </div>
</div>

app/views/shops/map.js.erb
/*
index.html.erbのscript内に
google mapのインスタンス変数である、
mapという変数があることに留意
*/

// (function(){
//   // 位置情報をもつ変数を用意
//   let pos = new google.maps.LatLng(
//    <%= @latlng[0] %>, //latitude
//    <%= @latlng[1] %>  //longitude
//   );

//   mapInstance.setCenter(pos)
//   let marker = new google.maps.Marker({
//     map: mapInstance,
//     position: pos
//   });
// })()

app/views/shops/new.html.erb
<div class="signup-page signup-shops">
  <div class="container">
    <div class="signup-header"><h1>お席貸出し新規登録</h1></div>
    <div class="shops-signup-form">
      <%= form_with model: @shop, local: true do |f| %>

      <div class="images">
        <div><%= f.label :店舗写真 %></div>
        <%= f.fields_for :images do |i| %>
              <button type="button" class="btn btn-outline-secondary rounded-pill">
                 <%= i.file_field :image_url, type: 'file',accept:'image/jpg,image/jpeg,image/gif,image/png'%>
              </button>
        <% end %>
      </div>

      <div class="main">
        <section class="main__block">
          <%= form_with model:@shop, local:true do |f| %>
            <div class="sell__block__form">
              <div class="sell__block__form__upload">
                <p>最大5枚までアップロードできます</p>

               <div id="image-box-1">
                  <div class="item-num-0" id="image-box__container">
                    <%= f.fields_for :images do |i| %>
                      <div class="input-area">
                        <%= i.file_field :image_url, type: 'file', name: "shop[images_attributes][][image_url]", value:"", style: "display:none", id:"img-file",accept:'image/jpg,image/jpeg,image/gif,image/png'%>

                        <label for="img-file">
                          <i class>
                            <div class="shop-images">
                              <ul>
                                <li><%= image_tag 'example_img_1.png' %></li>
                                <li><%= image_tag 'example_img_2.png' %></li>
                                <li><%= image_tag 'example_img_3.png' %></li>
                                <li><%= image_tag 'example_img_1.png' %></li>
                                <li><%= image_tag 'example_img_2.png' %></li>
                              </ul>
                            </div>
                          </i>
                        </label>

                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </section>
      </div>








      <div class="form-groups">

        <div class="form-group">
          <div><%= f.text_field :name, placeholder: "店舗名" %></div>
        </div>

        <div class="form-group">
          <div><%= f.text_field :address, placeholder: "住所" %></div>
        </div>

        <div class="form-group">
          <div><%= f.text_field :address, placeholder: "使用しているカラー剤" %></div>
        </div>

        <div class="form-group">
          <div><%= f.text_field :address, placeholder: "使用しているパーマ剤" %></div>
        </div>

        <div class="form-group">
          <div><%= f.text_field :address, placeholder: "使用しているトリートメント剤" %></div>
        </div>

        <div class="form-group">
          <div><%= f.text_field :address, placeholder: "道具、設備、アメニティ" %></div>
        </div>

        <div class="form-group">
            <div class="sns-account">
              <div><%= f.text_field :instagram_account, placeholder: "Instagram" %></div>
              <div><%= f.text_field :twitter_account, placeholder: "Twitter" %></div>
              <div><%= f.text_field :facebook_account, placeholder: "Facebook" %></div>
            </div>
        </div>

        <div class="form-group">
          <div><%= f.label :店舗紹介文 %></div>
          <div><%= f.text_area :introduction, size: "53x10" %></div>
        </div>
      </div>

      <div class="signup-submit-btn"><%= f.submit %></div>

      <div class="sign-up-option-btn">
        <%= link_to '戻る', root_path %>
        <%= link_to ' ログアウト ',destroy_user_session_path, method: :delete%>
      </div>

      </div>
    <% end %>
  </div>
</div>

app/views/shops/show.html.erb
<h1>詳細</h1>

<div>
	名称 : <%= @shop.name %>
</div>

<div>
	内容 : <%= @shop.description %>
</div>

<div>
  店舗写真 :
  <% @shop.images.each do |i| %>
   <%= image_tag i.image_url.to_s , width: '10%', height: '10%' %>
  <% end %>
</div>

<div>
	 住所 : <%= @shop.address %>
</div>

<div>
   緯度 : <%= @shop.latitude %>
</div>


<div>
   経度 : <%= @shop.longitude %>
</div>

<div id="map" style="width: 400px; height: 200px;"></div>


<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

<% if @shop.user_id == current_user.id %>
<h3><%= link_to '編集', edit_shop_path(@shop) %></h3>
<h3><%= link_to '削除', shop_path(@shop), method: :delete ,"data-confirm" => "本当に削除しますか？"%></h3>
<% end %>
<div>
	<%= link_to '戻る', shops_path %>
</div>

app/views/stylists/edit.html.erb
<h1>編集</h1>
<%= form_with model: @stylist, local: true do |f| %>

  <div><%= f.label :名称 %></div>
  <div><%= f.text_field :name %></div>

  <div><%= f.label :自己紹介 %></div>
  <div><%= f.text_field :description %></div>

  <div><%= f.label :活動拠点 %></div>
  <div></div>

  <div><%= f.label :得意なヘアスタイル %></div>
  <div><%= f.collection_select :hairstyle_id, Hairstyle.all,:id,:menu %></div>

  <div><%= f.label :開始日 %></div>
  <div><%= f.date_select :date_start %></div>

  <div><%= f.label :終了日 %></div>
  <div><%= f.date_select :date_fin %></div>

  <div><%= f.label :プロフィール画像 %></div>
  <div><%= f.file_field :image, multiple: true %></div>

  <div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', stylists_path %>

<%= link_to ' ログアウト ',destroy_user_session_path, method: :delete%>

app/views/stylists/index.html.erb
<section class="section">
    <div class="l-container">

      <div class="sectionTitle row">
        <h1 class="sectionTitle">美容師リスト</h1>
      </div>

      <div class="productList row">
        <% @stylists.each do |stylist| %>
        <div class="productList-stylist l-box">
          <a class="productList-stylist-link" href="/stylists/<%= stylist.id %>">
            <h2 class="productList-stylist-name"><%= stylist.last_name %></h2>
            <h2 class="productList-stylist-name"><%= stylist.first_name %></h2>
            <h2 class="productList-stylist-name"><%= stylist.user %></h2>
            <!-- <p class="productList-stylist-date-start"><%= stylist.date_start %></p> -->
          </a>
        </div>
        <% end %>
      </div>

      <div class="row">
          <div class="col-sm-10 col-sm-offset-1" style="text-align:center; padding:20px; font-size: 25px;">
              <%= paginate @stylists, class: "paginate" %>
          </div>
      </div>

    </div>
  </section>

app/views/stylists/new.html.erb
<div class="signup-page signup-stylists">
  <div class="container">
    <div class="signup-header"><h1>スタイリスト登録</h1></div>
    <div class="signup-form">
      <%= form_with model: @stylist, local: true do |f| %>

      <div class="form-description">
        <h3 class="text-left">ご本人確認</h3>
        <p>安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。<br>
           他のお客さまに公開されることはありません。
        </p>
      </div>

      <div class="form-group">
        <div class="form-header"><%= f.label :お名前（全角） %></div>
        <ul>
          <li><%= f.text_field :last_name %></li>
          <li><%= f.text_field :first_name %></li>
        </ul>
      </div>

      <div class="form-group">
        <div class="form-header"><%= f.label :お名前（カナ）   %></div>
        <ul>
          <li><%= f.text_field :last_name_kana %></li>
          <li><%= f.text_field :first_name_kana %></li>
        </ul>
      </div>

      <div class="form-group">
        <div><%= f.label :生年月日 %></div>
        <div><%= f.date_select :birthday %></div>
      </div>

      <div class="form-group">
        <div><%= f.label :メールアドレス %></div>
        <div><%= f.text_field :email %></div>
      </div>

      <div class="form-group">
        <div><%= f.label :パスワード %></div>
        <div><%= f.text_field :password %></div>
      </div>

      <div class="border"></div>

      <div class="form-description">
        <h3 class="text-left">プロフィール登録</h3>
        <p>以下の情報はアプリ内で公開されます。</p>
      </div>

      <div class="form-group">
        <div><%= f.label :プロフィール画像 %></div>
        <div><%= f.file_field :images, accept: "image/png, image/jpeg, image/gif" , multiple: true %></div>
      </div>

      <div class="form-group">
        <div><%= f.label :ニックネーム %></div>
        <div><%= f.text_field :name %></div>
      </div>

      <div class="form-group">
        <div><%= f.label :美容師歴 %></div>
        <div><%= f.select :career_years, options_for_select((1..50).to_a) %>年</div>
      </div>

      <div class="form-group">
        <div><%= f.label :主な活動エリア %></div>
        <div><%= f.collection_select :base_id, ::Base.all,:id,:base %></div>

      <div class="form-group">
        <div><%= f.label :得意なスタイル %></div>
        <ul class="skilled-style">
          <li><%= f.text_field :skilled_style1 %></li>
          <li><%= f.text_field :skilled_style2 %></li>
        </ul>
      </div>

      <div class="form-group">
        <div><%= f.label :SNSアカウント %><span class="notice">(例)https://www.instagram.com/matcha/</span></div>
          <div class="sns-account">
            <div><span>Instagram</span><%= f.text_field :instagram_account %></div>
            <div><span>Twitter</span><%= f.text_field :twitter_account %></div>
            <div><span>Facebook</span><%= f.text_field :facebook_account %></div>
          </div>
      </div>

      <div class="form-group">
        <div><%= f.label :自己紹介文 %></div>
        <div><%= f.text_area :introduction, size: "60x15" %></div>
      </div>

      <div class="signup-submit-btn"><%= f.submit %></div>

      <div class="sign-up-option-btn">
        <%= link_to '戻る', root_path %>
        <%= link_to ' ログアウト ',destroy_user_session_path, method: :delete%>
      </div>
    <% end %>
  </div>
</div>

app/views/stylists/show.html.erb
<h3>名前</h3>
<h3><%= @stylist.name %></h3>
<h3>自己紹介</h3>
<h3><%= @stylist.description %></h3>
<h3>プロフィール写真</h3>
<h3>
    <% @stylist.images.each do |image| %>
		<%= image_tag(image,size: "240x240", fallback:'no_image.png',size:'240x240') %>
	<% end %>
</h3>
<h3>開始日</h3>
<h3><%= @stylist.date_start %></h3>
<h3>終了日</h3>
<h3><%= @stylist.date_fin %></h3>
<h3></h3>
<h3></h3>

<% if @stylist.user_id == current_user.id %>
<h3><%= link_to '編集', edit_stylist_path(@stylist) %></h3>
<h3><%= link_to '削除', stylist_path(@stylist), method: :delete ,"data-confirm" => "本当に削除しますか？"%></h3>
<% end %>

<h3><%= link_to '戻る', stylists_path %></h3>