config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index' => 'home#index'

  devise_for :users,:controllers => {
        :registrations => 'users/registrations',
        :sessions => 'users/sessions',
        omniauth_callbacks: "users/omniauth_callbacks"
    }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  resources :shops
  resources :stylists

  get 'thank' => 'thank#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base.rb
class Base < ApplicationRecord
	has_many :stylists
end

app/models/basis.rb
class Basis < ApplicationRecord
end

app/models/hairstyle.rb
class Hairstyle < ApplicationRecord
	has_many :stylists
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :shop, optional: true
  	mount_uploader :image_url, ImageUploader
end

app/models/recommend.rb
class Recommend < ApplicationRecord
	has_many :shops
end

app/models/seet.rb
# class Seet < ApplicationRecord
# 	has_many :shops
# end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :user

	# belongs_to :seet

	has_many :images, dependent: :destroy
  	accepts_nested_attributes_for :images, allow_destroy: true

	geocoded_by :address
  	after_validation :geocode, if: :address_changed?, latitude: :latitude, longitude: :longitude
end

app/models/stylist.rb
class Stylist < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :base
	has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
  		   :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :omniauthable,
         omniauth_providers:%i(google)

  has_many :shops, dependent: :destroy
  has_many :stylists, dependent: :destroy

  protected
    def self.find_for_google(auth)
      user = User.find_by(email: auth.info.email)
      unless user
        user = User.create(name:     auth.info.name,
                          provider: auth.provider,
                          uid:      auth.uid,
                          token:    auth.credentials.token,
                          email:    auth.info.email,
                          password: Devise.friendly_token[0, 20],
                          meta:     auth.to_yaml)
      end
      user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    case resource
    # when Admin
    #   admin_posts_path
    when current_user
      home_index_path
    end
  end

#   def after_inactive_sign_up_path_for(resource)
#     case resource
#     # when Admin
#     #   admin_posts_path
#     root_path
#   end


# 　def after_sign_out_path_for(resource)
#   case resource
#     # when Admin
#     #   admin_posts_path
# 　  root_path
# 　end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
before_action :authenticate_user!,:ensure_correct_user,{only: [:edit, :update]}

  def new
    @shop = Shop.new
    @shop.images.build
  end

  def create
    @shop = Shop.create(shop_params)
    if @shop.save
      redirect_to shops_path , notice: '作成しました'
    else
      render 'index'
    end
  end

  def index
    @shops = Shop.page(params[:page]).per(12)
  end

  def show
    @shop = Shop.find(params[:id])
    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow shop.address
      marker.json({ address: shop.address })
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params)
    redirect_to shops_path
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path
  end



  private
    def shop_params
      params.require(:shop).permit(:name,
                                   :description,
                                   :address,
                                   :latitude,
                                   :longitude,
                                   :user_id,
                                   :seet_id,
                                   :recommend_id,
                                   images_attributes: [:image_url]
                                )
    end

    def ensure_correct_user
      @shop = Shop.find(params[:id])
      if current_user != @shop.user
        redirect_to shops_path
      end
    end


end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
before_action :authenticate_user!,:ensure_correct_user,{only: [:edit, :update]}

  def new
    @stylist = Stylist.new
  end

  def create
    @stylist = Stylist.new(stylist_params)
    if @stylist.save
      redirect_to stylists_path
    else
      render 'new'
    end
  end

  def index
    @stylists = Stylist.page(params[:page]).per(12)
  end

  def show
    @stylist = Stylist.find(params[:id])
    @stylists = Stylist.all
  end

  def edit
    @stylist = Stylist.find(params[:id])
  end

  def update
    @stylist = Stylist.find(params[:id])
    @stylist.update(stylist_params)
    redirect_to stylists_path
  end

  def destroy
    @stylist = Stylist.find(params[:id])
    @stylist.destroy
    redirect_to stylists_path
  end

private
  def stylist_params
    params.require(:stylist).permit(  :last_name,
                                      :first_name,
                                      :last_name_kana,
                                      :first_name_kana,
                                      :birthday,
                                      :email,
                                      :password,
                                      :name,
                                      :base_id,
                                      :user_id,
                                      :recommend_id,
                                      :career_years,
                                      :skilled_style1,
                                      :skilled_style2,
                                      :description,
                                      images: []
                                  )
  end

  def ensure_correct_user
    @stylist = Stylist.find(params[:id])
    if current_user != @stylist.user
      redirect_to stylists_path
    end
  end

end

app/controllers/thank_controller.rb
class ThankController < ApplicationController
  def index
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/helpers/thank_helper.rb
module ThankHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag "home", :media => "all" %>

<div class="top-wrapper">
		<div class="top-menu">
			<ul>
    			<li><i class="fas fa-cut"></i><%= link_to "美容師さんはこちら" ,new_stylist_path %></li>
    			<li><i class="fas fa-search"></i><%= link_to "美容師さんを探す" , stylists_path %></li>
    			<li><i class="fas fa-chair"></i><%= link_to " 空いている席を貸す " ,new_shop_path %></li>
    		</ul>
    </div>
	<div class="container top-container">
		<div class="top-message-img">
			<%= image_tag 'top_message_icon.png'  %>
		</div>
		<div class="top-message">
			<h1>美容をツナグ。美容でツナグ。</h1>
			<div>Matcha</div>
			<p>
				時間と場所にとらわれない美容師という働き方 <br>
				お店は空いている施術台を貸出して有効活用 <br>
				専属の美容師を見つけてストレスフリーな環境へ
			</p>
		</div>
		<div class="media-top-message">
    	<h1>Matcha</h1>
			<p>美容専門マッチングアプリ</p>
			<div class="btn">
				<%= link_to "はじめる", new_user_registration_path %>
			</div>
    </div>
  </div>
</div>
<div class="about-service-box-wrapper">
	<h3>Matchaとは</h3>
	<div class="container">
		<div class="about-service-box">
			<div class="about-service-box-item">
				<div class="about-service-box-item-head">For Stylists</div>
				<div><%= image_tag 'top_icon_1.png' %></div>
				<p>
					Matchaを使って <br>
					自由な働き方を実現しましょう。 <br>
					美容師さんの施術に対し <br>
					利益率90%を目指します。
				</p>
			</div>
			<div class="about-service-box-item">
				<div class="about-service-box-item-head">For Customers</div>
				<div><%= image_tag 'top_icon_2.png' %></div>
			  <p>
					あなたの理想とする <br>
					スタイルを得意とする専属美容師さん <br>
					をMatchaで見つけましょう。
				</p>
			</div>
			<div class="about-service-box-item">
				<div class="about-service-box-item-head">For Salon owners</div>
				<div><%= image_tag 'top_icon_3.png' %></div>
				<p>
					空いている"施術台"を <br>
					有効活用しませんか？ <br>
					Matchaで席を貸し出して <br>
					売り上げをあげましょう。
				</p>
			</div>
		</div>
	</div>
</div>
<%#
<div class="contents-wrapper">
	<div class="container">
		<div class="contents-box">
			<div class="contents-box-item">
				<div class="contents-box-item-message">
					<h3>For Stylist</h3>
					<p>店舗を必要としないため、美容師さんに従来より高い利益率を還元することができます。時間と場所を選ばないため、副業美容師という新しい働き方も可能になります。店舗を必要としないため、美容師さんに従来より高い利益率を還元することができます。時間と場所を選ばないため、副業美容師という新しい働き方も可能になります。あ</p>
				</div>
			</div>
			<div class="contents-box-item">
				<div class="contents-box-item-message">
					<h3>For Customer</h3>
					<p>店舗を必要としないため、美容師さんに従来より高い利益率を還元することができます。時間と場所を選ばないため、副業美容師という新しい働き方も可能になります。店舗を必要としないため、美容師さんに従来より高い利益率を還元することができます。時間と場所を選ばないため、副業美容師という新しい働き方も可能になります。</p>
				</div>
			</div>
			<div class="contents-box-item">
				<div class="contents-box-item-message">
					<h3>For Salon owner</h3>
					<p>店舗を必要としないため、美容師さんに従来より高い利益率を還元することができます。時間と場所を選ばないため、副業美容師という新しい働き方も可能になります。店舗を必要としないため、美容師さんに従来より高い利益率を還元することができます。時間と場所を選ばないため、副業美容師という新しい働き方も可能になります。</p>
				</div>
			</div>
		</div>
	</div>
</div>
%>


<p id="pageTop">
  <a href="#"><i class="fas fa-angle-double-up"></i></a>
</p>

app/views/thank/index.html.erb
<div class="main thanks-page">
  <div class="container">
    <div class="thanks-page-box">
      <div class="heading">
        <!-- 〇〇〇〇様 <br> -->
        会員登録ありがとうございます。
      </div>
      <div class="text">
        <p>
          ご登録メールアドレスへ本登録URLが記載されたメールをお送りいたしました。
          URLから本登録をお済ませください。
        </p>
        <%= link_to "トップページへ戻る", root_path %>
        <p>
          Matchaからのメールが届かない場合は、<%= link_to "こちら", root_path %>から再度メールの送信をお願い致します。
        </p>
      </div>
    </div>
  </div>
</div>